version: '3.8'

services:
  webapi:
    build:
      context: ./WebApiStudents
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=StudentsDb;User Id=sa;Password=T2ZvtfXHPzw75yESGFBMQ9VLDau3KRqdsNUmj4rA;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "T2ZvtfXHPzw75yESGFBMQ9VLDau3KRqdsNUmj4rA"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: {}
